# Dependencies
markdown:         kramdown
highlighter:      rouge


# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly - no longer supported by github
permalink:           pretty
#relative_permalinks: true


# Setup
title:              'Johannes Peter'
tagline:            'Assorted Code snippets and Dev devices'
description:        'Programmer, Graphic Designer, Web Developer and DigiPen Student' 
url:                http://blog.johannesmp.com
baseurl:            ''
paginate:           5
excerpt_separator:  <!-- more -->
repository:         'JohannesMP/com.johannesmp.blog'

# About/contact
author:
  name:                 Johannes Peter
  url:                  https://twitter.com/jo_shadow
  email:                joshadow@gmail.com
  email_md5:            9fa2131cef896ad0596d4fafc99f09d8
  github:               JohannesMP
  twitter:              jo_shadow
  linkedin:             johannesmp
  disqus_shortname:     JohannesMP
  google_analytics_id:  UA-67064476-1
  google_analytics_url: auto


# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed


# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/JohannesMP/com.johannesmp.blog


# This is the list of pages to incldue in the header of the website.
# pages_list:       {'About':'/about','Archive':'/archive','Feed':'/atom.xml'}
